"""create staging tables (transporteurs, tournees, livraisons, commandes_clients)

Revision ID: d9f35cd9fa75
Revises:
Create Date: 2026-08-26 14:18:29.834987

Ne gère que les 4 tables modélisées par C11 (voir
src/datacore/storage/staging/models.py). Les tables FluxPro
(data/raw/schema.sql, issue #7) et historique_expeditions
(sql/historique_schema.sql, C9) sont hors du périmètre Alembic : les
`op.drop_table(...)` que --autogenerate proposait pour elles (parce
qu'elles n'apparaissent pas dans `target_metadata`) ont été retirés à
la main -- elles ne doivent jamais être supprimées par cette migration.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd9f35cd9fa75'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commandes_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client', sa.String(length=50), nullable=False),
    sa.Column('commande_id', sa.String(length=30), nullable=False),
    sa.Column('date_commande', sa.Date(), nullable=False),
    sa.Column('sku', sa.String(length=20), nullable=False),
    sa.Column('libelle_produit', sa.String(length=150), nullable=True),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('poids_kg', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('entrepot', sa.String(length=20), nullable=True),
    sa.Column('chaine_froid_requise', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transporteurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transporteur_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('vehicule_id', sa.String(length=20), nullable=True),
    sa.Column('chauffeur', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['transporteur_id'], ['transporteurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livraisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournee_id', sa.Integer(), nullable=False),
    sa.Column('tracking_number', sa.String(length=20), nullable=False),
    sa.Column('adresse_livraison', sa.String(length=200), nullable=True),
    sa.Column('statut', sa.String(length=30), nullable=True),
    sa.Column('heure_estimee', sa.String(length=10), nullable=True),
    sa.Column('heure_reelle', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['tournee_id'], ['tournees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livraisons')
    op.drop_table('tournees')
    op.drop_table('transporteurs')
    op.drop_table('commandes_clients')
    # ### end Alembic commands ###
