"""add partial unique index enforcing one current dim_client per client_id

Revision ID: 44a800999124
Revises: f6242611380a
Create Date: 2026-09-21 16:13:11.818901

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '44a800999124'
down_revision: str | Sequence[str] | None = 'f6242611380a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'uq_dim_client_courant', 'dim_client', ['client_id'],
        unique=True, schema='dimensions', postgresql_where=sa.text('is_current'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'uq_dim_client_courant', table_name='dim_client',
        schema='dimensions', postgresql_where=sa.text('is_current'),
    )
    # ### end Alembic commands ###
