"""create warehouse schemas dimensions exploitation commercial

Revision ID: 87dcc1313f23
Revises: 
Create Date: 2026-08-28 10:18:10.536379

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '87dcc1313f23'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Les 3 schemas Postgres (un par datamart + un pour les dimensions
    # conformees, voir warehouse/models.py) ne sont pas crees
    # automatiquement par create_table(schema=...) : autogenerate ne les
    # detecte/emet jamais, a creer explicitement avant les tables.
    op.execute("CREATE SCHEMA IF NOT EXISTS dimensions")
    op.execute("CREATE SCHEMA IF NOT EXISTS exploitation")
    op.execute("CREATE SCHEMA IF NOT EXISTS commercial")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_categorie',
    sa.Column('categorie_key', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('categorie_key'),
    sa.UniqueConstraint('libelle'),
    schema='dimensions'
    )
    op.create_table('dim_client',
    sa.Column('client_key', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False, comment='clé naturelle FluxPro'),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('secteur', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('client_key'),
    schema='dimensions'
    )
    op.create_table('dim_site',
    sa.Column('site_key', sa.Integer(), nullable=False),
    sa.Column('entrepot_id', sa.Integer(), nullable=False, comment='clé naturelle FluxPro'),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('ville', sa.String(length=100), nullable=False),
    sa.Column('capacite_palettes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('site_key'),
    schema='dimensions'
    )
    op.create_table('dim_temps',
    sa.Column('date_key', sa.Integer(), nullable=False, comment='YYYYMMDD'),
    sa.Column('date_complete', sa.Date(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('trimestre', sa.Integer(), nullable=False),
    sa.Column('mois', sa.Integer(), nullable=False),
    sa.Column('nom_mois', sa.String(length=20), nullable=False),
    sa.Column('jour_semaine', sa.Integer(), nullable=False),
    sa.Column('numero_semaine', sa.Integer(), nullable=False),
    sa.Column('est_weekend', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('date_key'),
    sa.UniqueConstraint('date_complete'),
    schema='dimensions'
    )
    op.create_table('dim_transporteur',
    sa.Column('transporteur_key', sa.Integer(), nullable=False),
    sa.Column('transporteur_id', sa.Integer(), nullable=True,
              comment='clé naturelle, absente pour le membre Inconnu'),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('transporteur_key'),
    schema='dimensions'
    )
    op.create_table('dim_produit',
    sa.Column('produit_key', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False, comment='clé naturelle FluxPro'),
    sa.Column('sku', sa.String(length=20), nullable=False),
    sa.Column('libelle', sa.String(length=150), nullable=False),
    sa.Column('poids_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('temperature_dirigee', sa.Boolean(), nullable=True),
    sa.Column('categorie_key', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categorie_key'], ['dimensions.dim_categorie.categorie_key'], ),
    sa.PrimaryKeyConstraint('produit_key'),
    schema='dimensions'
    )
    op.create_table('fait_expedition',
    sa.Column('expedition_key', sa.Integer(), nullable=False),
    sa.Column('client_key', sa.Integer(), nullable=True),
    sa.Column('site_key', sa.Integer(), nullable=False),
    sa.Column('categorie_key', sa.Integer(), nullable=False),
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('transporteur_key', sa.Integer(), nullable=True),
    sa.Column('tracking_number', sa.String(length=20), nullable=True,
              comment='dimension dégénérée, absente côté historique'),
    sa.Column('source_systeme', sa.String(length=20), nullable=False,
              comment='FluxPro_TransFlow ou Historique'),
    sa.Column('poids_kg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('delai_livraison_jours', sa.Integer(), nullable=True),
    sa.Column('cout_transport_eur', sa.Numeric(precision=8, scale=2), nullable=True,
              comment='absent côté FluxPro/TransFlow'),
    sa.Column('statut', sa.String(length=30), nullable=False),
    sa.Column('livre_a_lheure', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['categorie_key'], ['dimensions.dim_categorie.categorie_key'], ),
    sa.ForeignKeyConstraint(['client_key'], ['dimensions.dim_client.client_key'], ),
    sa.ForeignKeyConstraint(['date_key'], ['dimensions.dim_temps.date_key'], ),
    sa.ForeignKeyConstraint(['site_key'], ['dimensions.dim_site.site_key'], ),
    sa.ForeignKeyConstraint(['transporteur_key'],
                             ['dimensions.dim_transporteur.transporteur_key'], ),
    sa.PrimaryKeyConstraint('expedition_key'),
    schema='exploitation'
    )
    op.create_table('fait_commande',
    sa.Column('commande_ligne_key', sa.Integer(), nullable=False),
    sa.Column('client_key', sa.Integer(), nullable=False),
    sa.Column('site_key', sa.Integer(), nullable=False),
    sa.Column('produit_key', sa.Integer(), nullable=False),
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('commande_id', sa.String(length=30), nullable=False,
              comment='dimension dégénérée, clé FluxPro'),
    sa.Column('quantite_commandee', sa.Integer(), nullable=False),
    sa.Column('poids_ligne', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('statut_commande', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['client_key'], ['dimensions.dim_client.client_key'], ),
    sa.ForeignKeyConstraint(['date_key'], ['dimensions.dim_temps.date_key'], ),
    sa.ForeignKeyConstraint(['produit_key'], ['dimensions.dim_produit.produit_key'], ),
    sa.ForeignKeyConstraint(['site_key'], ['dimensions.dim_site.site_key'], ),
    sa.PrimaryKeyConstraint('commande_ligne_key'),
    schema='commercial'
    )
    op.create_table('fait_stock',
    sa.Column('stock_key', sa.Integer(), nullable=False),
    sa.Column('site_key', sa.Integer(), nullable=False),
    sa.Column('produit_key', sa.Integer(), nullable=False),
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('quantite_stock', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['date_key'], ['dimensions.dim_temps.date_key'], ),
    sa.ForeignKeyConstraint(['produit_key'], ['dimensions.dim_produit.produit_key'], ),
    sa.ForeignKeyConstraint(['site_key'], ['dimensions.dim_site.site_key'], ),
    sa.PrimaryKeyConstraint('stock_key'),
    sa.UniqueConstraint('site_key', 'produit_key', 'date_key', name='uq_fait_stock_grain'),
    schema='exploitation'
    )
    # ### end Alembic commands ###

    # Acces configures (C14) : role de lecture seule bi_reader (cree par
    # scripts/init_omega_bi_db.sh, avant cette migration) -- lecture sur
    # les 3 schemas, y compris les tables futures (ALTER DEFAULT
    # PRIVILEGES couvre les prochaines migrations sans regrant manuel).
    for schema in ("dimensions", "exploitation", "commercial"):
        op.execute(f"GRANT USAGE ON SCHEMA {schema} TO bi_reader")
        op.execute(f"GRANT SELECT ON ALL TABLES IN SCHEMA {schema} TO bi_reader")
        op.execute(
            f"ALTER DEFAULT PRIVILEGES IN SCHEMA {schema} "
            f"GRANT SELECT ON TABLES TO bi_reader"
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fait_stock', schema='exploitation')
    op.drop_table('fait_commande', schema='commercial')
    op.drop_table('fait_expedition', schema='exploitation')
    op.drop_table('dim_produit', schema='dimensions')
    op.drop_table('dim_transporteur', schema='dimensions')
    op.drop_table('dim_temps', schema='dimensions')
    op.drop_table('dim_site', schema='dimensions')
    op.drop_table('dim_client', schema='dimensions')
    op.drop_table('dim_categorie', schema='dimensions')
    # ### end Alembic commands ###

    op.execute("DROP SCHEMA IF EXISTS exploitation CASCADE")
    op.execute("DROP SCHEMA IF EXISTS commercial CASCADE")
    op.execute("DROP SCHEMA IF EXISTS dimensions CASCADE")
