"""add gouvernance schema (journal_operations) and SLA views

Revision ID: f6242611380a
Revises: ad009b506239
Create Date: 2026-09-21 13:57:00.261542

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f6242611380a'
down_revision: str | Sequence[str] | None = 'ad009b506239'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS gouvernance")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'journal_operations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('operation', sa.String(length=50), nullable=False,
                   comment='ex. load_warehouse, backup_complet'),
        sa.Column('demarre_le', sa.DateTime(), nullable=False),
        sa.Column('termine_le', sa.DateTime(), nullable=True),
        sa.Column('statut', sa.String(length=20), nullable=False,
                   comment='en_cours, succes ou echec'),
        sa.Column('details', sa.Text(), nullable=True,
                   comment='résumé libre (ex. comptes de lignes chargées)'),
        sa.Column('erreur', sa.Text(), nullable=True,
                   comment="message d'erreur si statut = echec"),
        sa.PrimaryKeyConstraint('id'),
        schema='gouvernance',
    )
    # ### end Alembic commands ###

    # Vues d'indicateurs de service (C16) -- pas modelisables comme Table
    # SQLAlchemy classique, creees en SQL brut via op.execute(), meme
    # principe que livraisons_avec_statut (staging, C11).

    op.execute("""
        CREATE VIEW exploitation.v_taux_service_client AS
        SELECT
            dc.nom AS client,
            count(*) AS nb_expeditions,
            round(
                100.0 * sum(CASE WHEN fe.livre_a_lheure THEN 1 ELSE 0 END) / count(*),
                1
            ) AS taux_service_pct
        FROM exploitation.fait_expedition fe
        JOIN dimensions.dim_client dc ON dc.client_key = fe.client_key
        WHERE fe.source_systeme = 'FluxPro_TransFlow' AND fe.livre_a_lheure IS NOT NULL
        GROUP BY dc.nom
    """)

    op.execute("""
        CREATE VIEW exploitation.v_delai_moyen_transporteur AS
        SELECT
            dt.nom AS transporteur,
            count(*) AS nb_expeditions,
            round(avg(fe.delai_livraison_jours)::numeric, 1) AS delai_moyen_jours
        FROM exploitation.fait_expedition fe
        JOIN dimensions.dim_transporteur dt ON dt.transporteur_key = fe.transporteur_key
        WHERE fe.delai_livraison_jours IS NOT NULL
        GROUP BY dt.nom
    """)

    op.execute("""
        CREATE VIEW exploitation.v_stock_disponible_site AS
        SELECT
            ds.nom AS entrepot,
            sum(fs.quantite_stock) AS quantite_totale,
            count(DISTINCT fs.produit_key) AS nb_references
        FROM exploitation.fait_stock fs
        JOIN dimensions.dim_site ds ON ds.site_key = fs.site_key
        GROUP BY ds.nom
    """)

    op.execute("""
        CREATE VIEW gouvernance.v_dernieres_operations AS
        SELECT
            operation, demarre_le, termine_le, statut,
            EXTRACT(EPOCH FROM (termine_le - demarre_le)) AS duree_secondes
        FROM gouvernance.journal_operations
        ORDER BY demarre_le DESC
        LIMIT 20
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP VIEW IF EXISTS gouvernance.v_dernieres_operations")
    op.execute("DROP VIEW IF EXISTS exploitation.v_stock_disponible_site")
    op.execute("DROP VIEW IF EXISTS exploitation.v_delai_moyen_transporteur")
    op.execute("DROP VIEW IF EXISTS exploitation.v_taux_service_client")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal_operations', schema='gouvernance')
    # ### end Alembic commands ###

    op.execute("DROP SCHEMA IF EXISTS gouvernance CASCADE")
